name       : redeclipse
version    : 1.6.0
release    : 2
source     :
    - https://github.com/red-eclipse/base/releases/download/v1.6.0/redeclipse_1.6.0_combined.tar.bz2 : 5a14ffd5297e8471cbbe5fe77297945c756361e0fd0f3febf94c1d17004b4aa9
license    :
    - CC-BY-3.0
    - CC-BY-SA-3.0
    - CC0-1.0
    - Public-Domain
    - Zlib
component  : games.action
summary    : A free first-person arena shooter
description: |
    Red Eclipse is a fun-filled new take on the first-person arena shooter, built as a total conversion of Cube Engine 2
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(xkbfile)
    - ed
build      : |
    %make -C src
install    : |
    %make_install -C src prefix=/usr libexecdir=$installdir/usr/share system-install
