name       : redeclipse
version    : 1.5.8
release    : 1
source     :
    - https://github.com/red-eclipse/base/releases/download/v1.5.8/redeclipse_1.5.8_combined.tar.bz2 : 432153c7bf45072494cf1ff17f52a720221f2e18f9e7684a0696354188c85cc7
license    : zlib
component  : games.action
summary    : A free first-person arena shooter
description: |
    Red Eclipse is a fun-filled new take on the first-person arena shooter, built as a total conversion of Cube Engine 2
builddeps   :
    - pkgconfig(gl)
    - pkgconfig(SDL2_image)
    - pkgconfig(SDL2_mixer)
    - pkgconfig(xkbfile)
    - ed
build      : |
    cd src
    %make client server
install    : |
    cd src
    %make_install prefix=/usr system-install